"""Fix relationship conflict between User and Resume

Revision ID: 7d914a6b3b48
Revises: efd7d125eae3
Create Date: 2025-02-06 18:52:15.143016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d914a6b3b48'
down_revision = 'efd7d125eae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.alter_column('skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint('resumes_email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_resumes_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_resumes_job_role'), ['job_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_uploaded_at'), ['uploaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint('resumes_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('legal_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resumes_user_id_fkey', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_resumes_user_id'))
        batch_op.drop_index(batch_op.f('ix_resumes_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_resumes_job_role'))
        batch_op.drop_index(batch_op.f('ix_resumes_email'))
        batch_op.create_unique_constraint('resumes_email_key', ['email'])
        batch_op.alter_column('skills',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###
