"""Added legal_details column to users

Revision ID: c6f976cdb050
Revises: 7d914a6b3b48
Create Date: 2025-02-06 19:21:15.499155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f976cdb050'
down_revision = '7d914a6b3b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_details', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('legal_details')

    # ### end Alembic commands ###
