"""Initial migration

Revision ID: efd7d125eae3
Revises: 01cb2ce5ec89
Create Date: 2025-02-04 02:37:49.485291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efd7d125eae3'
down_revision = '01cb2ce5ec89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index('idx_email')
        batch_op.drop_index('idx_job_role')
        batch_op.drop_index('idx_skills', postgresql_using='gin')

    op.drop_table('resumes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('legal_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))

    op.create_table('resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('job_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumes_pkey'),
    sa.UniqueConstraint('email', name='resumes_email_key')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index('idx_skills', ['skills'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_job_role', ['job_role'], unique=False)
        batch_op.create_index('idx_email', ['email'], unique=False)

    # ### end Alembic commands ###
